import {
    property_input,
    property_switch,
    property_inputNumber,
    property_radio,
    property_checkbox,
    property_select,
    property_pic,
    property_file,
    property_textarea,
    property_datamodal,
    property_date,
    property_time,
    property_caption,
    property_row,
    property_col,
    property_tabs,
    property_tabPane,
    property_tip,
    property_form,
    property_card,
    property_slider
} from '../propertys'
import { DynamicComponentType} from '../../interfaces'
import { DynamicComponentGroup } from '../../enums'
export const dynamicComponentTypes: Array<DynamicComponentType> = [
    { componentName: 'ElsInput',  label: '输入框', value: "Input", type: "Input", dataTypes: ['String'], defaultPropertys: {}, propertys: property_input, group: DynamicComponentGroup.Form,formItem:true ,isShow:true},
    { componentName: 'ElsTextarea', label: '文本域', value: 'Textarea', type: "Textarea", dataTypes: ['String'], defaultPropertys: {}, propertys: property_textarea, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsInputNumber', label: '数字输入框', value: 'InputNumber', type: "InputNumber", dataTypes: ['Number'], defaultPropertys: {}, propertys: property_inputNumber, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsSlider', label: 'Slider滑块', value: 'Slider', type: "Slider", dataTypes: ['Number'], defaultPropertys: {}, propertys: property_slider, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsSwitch', label: '开关', value: 'Switch', type: "Switch", dataTypes: ['Bool', 'String', 'Number'], defaultPropertys: {}, propertys: property_switch, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsCheckbox', label: '多选列表', value: 'Checkbox', type: "Checkbox", dataTypes: ['String'], defaultPropertys: {}, propertys: property_checkbox, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsSelect', label: '下拉列表', value: 'Select', type: "Select", dataTypes: ['String', 'Number', 'Bool'], defaultPropertys: {}, propertys: property_select, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsRadio', label: '单选列表', value: 'Radio', type: "Radio", dataTypes: ['String', 'Number', 'Bool'], defaultPropertys: {}, propertys: property_radio, group: DynamicComponentGroup.Form,formItem:true ,isShow:true},
    { componentName: 'ElsUpload', label: '图片', value: 'UploadPic', type: "UploadPic", dataTypes: ['String'], defaultPropertys: { 'type': 'Pic' }, propertys: property_pic, group: DynamicComponentGroup.Form,formItem:true ,isShow:true},
    { componentName: 'ElsUpload', label: '图集', value: 'UploadMutiPic', type: "UploadMutiPic", dataTypes: ['String'], defaultPropertys: { 'type': 'Pic', 'multiple': true }, propertys: property_pic, group: DynamicComponentGroup.Form,formItem:true ,isShow:true},
    { componentName: 'ElsUpload', label: '文件', value: 'UploadFile', type: "UploadFile", dataTypes: ['String'], defaultPropertys: { 'type': 'File' }, propertys: property_file, group: DynamicComponentGroup.Form,formItem:true,isShow:true },
    { componentName: 'ElsDataModal', label: '弹窗', value: 'DataModal', type: "DataModal", dataTypes: ['String'], defaultPropertys: {}, propertys: property_datamodal, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsDatePicker', label: '日期选择器', value: 'Datepicker', type: "Datepicker", dataTypes: ['String', 'Number'], defaultPropertys: {}, propertys: property_date, group: DynamicComponentGroup.Form ,formItem:true,isShow:true},
    { componentName: 'ElsTimePicker', label: '时间选择器', value: 'Timepicker', type: "Timepicker", dataTypes: ['String', 'Number'], defaultPropertys: {}, propertys: property_time, group: DynamicComponentGroup.Form,formItem:true ,isShow:true},
    { componentName: 'ElsRow', label: '栅格行', value: 'Row', type: "Row", dataTypes: ['None'], defaultPropertys: {}, propertys: property_row, group: DynamicComponentGroup.Container,formItem:false ,isShow:true},
    { componentName: 'ElsCol', label: '栅格列', value: 'Col', type: "Col", dataTypes: ['None'], defaultPropertys: {}, propertys: property_col, group: DynamicComponentGroup.Container,restrictParent:'Row',formItem:false,isShow:true},
    { componentName: 'ElsTabs', label: 'Tabs标签页', value: 'Tabs', type: "Tabs",  dataTypes: ['String', 'Number'], defaultPropertys: {}, propertys: property_tabs, group: DynamicComponentGroup.Container,restrictChild:'TabPane' ,formItem:true,isShow:true },
    { componentName: 'ElsOption', label: 'Tabs选项', value: 'TabPane', type: "Option", dataTypes: ['None'], defaultPropertys: {}, propertys: property_tabPane, group: DynamicComponentGroup.Container,restrictParent:'Tabs',formItem:true,isShow:true},
    { componentName: 'ElsCaption', label: '分隔描述', value: 'Caption', type: "Caption", dataTypes: ['None','String'], defaultPropertys: {}, propertys: property_caption, group: DynamicComponentGroup.Show ,formItem:true,isShow:true},
    { componentName: 'ElsTip', label: '页面提示', value: 'Tip', type: "Tip", dataTypes: ['None'], defaultPropertys: {}, propertys: property_tip, group: DynamicComponentGroup.Show ,formItem:false,isShow:true},
    { componentName: 'ElsForm', label: 'Form表单', value: 'Form', type: "Form", dataTypes: ['None'], defaultPropertys: {}, propertys: property_form, group: DynamicComponentGroup.Container ,formItem:false,isShow:false},
    { componentName: 'ElCard', label: 'Card卡片', value: 'Card', type: "Card", dataTypes: ['None'], defaultPropertys: {}, propertys: property_card, group: DynamicComponentGroup.Container ,formItem:false,isShow:true},

]
