import {ValidType} from '../enums'
export interface ColumnProps {
    prop?: string,
    sortable?: string | boolean,
    type?: string,
    isLocaleString?: boolean,
    isHb?: boolean,
    isTb?: boolean,
    isEdit?: boolean,
    editFields?: string,
    isCustomEdit?: boolean,
    sortExpress?: string,
    dateFormatter?: string,
    isExport?: boolean,
    triggerActionName?: string,
    triggerMenuId?: string,
    headerFormatter?: string,
    mergeRow?: boolean,
    mergeRowByFieldname?: string,
    mergeFieldname?: string,
    mergeMethod?: Function,
    mergeSum?: boolean,
    showSummary?: boolean,
    summaryMethod?: Function,
    summaryValue?: string | number,
    trueLabel?: string,
    falseLabel?: string | number | boolean,
    trueValue?: string | number | boolean,
    trueClass?: string,
    falseClass?: string,
    enumShowType?: string,
    enumEqualType?: string,
    enumData?: any,
    enumNoneLabel?: string,
    hasBottomBorder?: boolean,
    imageStyle?: string,
    imageEmptyDesc?: string,
    isPreview?: boolean,
    isFold?: boolean,
    unFoldCount?: number,
    selectButtonLabel?: string,
    sortMethod?: Function,
    columnKey?: string,
    isAvgDay?: boolean,
    sortData?: any,
    tipContent?: string,
    align?:string,
    headerAlign?:string,
    required?:boolean,
    requiredMessage?:string,
    validType?:ValidType,
    validExpression?:string,
    validMessage?:string,
    validMethod?:Function,
    validTrigger?:string,
}